<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Services.Catalog.Domain</RootNamespace>
    <AssemblyName>Services.Catalog.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuldingBlock.Domain\BuldingBlock.Domain.csproj" />
  </ItemGroup>

</Project>
